---
language: minimal

env:
  - distro: debian9
  - distro: debian8
  - distro: centos7
  - distro: fedora27
  - distro: ubuntu1804
  - distro: ubuntu1604

matrix:
  # TODO: Fix these failures?
  allow_failures:
    - env: distro=centos7
    - env: distro=fedora27
    - env: distro=ubuntu1604

install:
  - docker pull geerlingguy/docker-${distro}-ansible
  - container_id=$(mktemp)
  - >
    docker run --detach --privileged
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume ${PWD}:/etc/ansible/roles/ansible-role-lighttpd:ro
    --publish 80:80
    geerlingguy/docker-${distro}-ansible:latest > ${container_id}

script:
  # Check Ansible role/playbook syntax.
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook --syntax-check /etc/ansible/roles/ansible-role-lighttpd/tests/test.yml

  # Ensure the role/playbook runs without errors or failures.
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/ansible/roles/ansible-role-lighttpd/tests/test.yml

  # Run the role/playbook again to test idempotence.
  - idempotence=$(mktemp)
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/ansible/roles/ansible-role-lighttpd/tests/test.yml
    | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - curl http://localhost/

after_script:
  - docker rm -f "$(cat ${container_id})"
