---
- name: Install Lighttpd.
  apt:
    name: lighttpd
    state: present
    update_cache: true

- name: Write Lighttpd configuration file.
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: "640"
    # TODO: Figure out how to get validation to work when the
    #       `include_shell` directive loads a relative path.
    #       The issue is that Lighttpd will test against the
    #       ansible `remote_tmp` path (usually `~/.ansible/tmp`)
    #       but of course, there are no Lighttpd config files there.
    #validate: "lighttpd -tt -f %s"
  notify: Restart Lighttpd.
