---
- name: Install Lighttpd.
  package:
    name: lighttpd
    state: present

- name: Write Lighttpd configuration file.
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: "640"
    validate: "lighttpd -tt -f %s"
  notify: Restart Lighttpd.
